### PR TITLE
Show payment success sheet after completing LN payments

### LINKED ISSUE #362: Show payment success sheet after completing LN payments
- Wait at least 10 seconds for `PaymentSucceeded` event for LN payments*, then show payment success sheet.
- Pop early if payment fails.

*: LNInvoice & LNOffer

### PR DESCRIPTION
**Pull request by erdemyerebasmaz**
Fixes #362

---

This PR adds payment event tracking for outgoing payments.

After sending a LN payment*, `ProcessingPaymentSheet` waits at least 10 seconds for a `PaymentSucceeded` event for the corresponding LN payment and then:
- shows the payment sent content if the payment is successful.
- pops early if an error occurs.

#### Changelist:
- feat: Track outgoing payments in `trackPaymentEvents` 62d970c
- feat: Show payment sent sheet after completing LN payments f943a83
  - ⚠️ There are several refactoring changes in this PR, which might make it difficult to review everything. I recommend focusing only on `isLnPayment` related logic, or simply test the behavior on the online build.

_*: Ln Payments are of type`LNInvoice` & `LNOffer`._

### CODE REVIEW

**Comment by erdemyerebasmaz** [comment]
### Testing notes:

- [ ] Pay either a Bolt 11 invoice or Bolt 12 offer
- [ ] If payment succeeds in 10 seconds, you'll see **Payment Sent!** screen
   - [ ] Bottom sheet is popped without **Payment Sent!** confirmation on timeout(10 seconds)
- [ ] If payment fails, the payment sheet is popped early and an error flushbar is shown to the user


Would like to hear your input on timeout duration, let us know if you find it to be too short with respect to payment completion times.

---

### Builds:
- **iOS:** `Version 0.1.0 (6322.1)` on TestFlight

CC: @Nackoo2000

**Comment by erdemyerebasmaz** [comment]
### Success Case:

https://github.com/user-attachments/assets/d518145d-1682-4795-9502-7da8e124fd79

**Review by dangeross — APPROVED** [review]
LGTM. Couldn't test as the CI build failed

File: lib/widgets/payment_status_sheets/processing_payment_sheet.dart [hunk 1]
```diff
@@ -54,70 +61,141 @@ class ProcessingPaymentSheetState extends State<ProcessingPaymentSheet> {
...
+  }
+
+  void _trackLnPaymentEvents(SendPaymentResponse payResult) {
+    final InputCubit inputCubit = context.read<InputCubit>();
+
+    final Future<void> paymentSuccessFuture = inputCubit.trackPaymentEvents(
+      payResult.payment.destination,
+      paymentType: PaymentType.send,
+    );
+    final Future<void> timeoutFuture = Future<void>.delayed(const Duration(seconds: 10));
```
Comment (roeierez) [inline lib/widgets/payment_status_sheets/processing_payment_sheet.dart:108]: Perhaps we can use the timeout function on future? https://api.flutter.dev/flutter/dart-async/Future/timeout.html

**Review by danielgranhao — APPROVED** [review]
utACK

**Comment by Nackoo2000** [comment]
image
When doing this I am trying to make a payment and turning off the internet connection before the payment is sent. 
The flushbar is shown but then the app is stuck on the Processing Payment screen.

Even when turning on the internet and the payment is received on the other side Misty is still stuck on the Processing Payment screen.
[l-breez.logs (63).zip](https://github.com/user-attachments/files/18963339/l-breez.logs.63.zip)
