### PR TITLE
fix: Resolve HydratedBloc persistence issues in obfuscated release builds

### LINKED ISSUE #491: Investigate why profile name is not persisted after updating on TestFlight

### PR DESCRIPTION
**Pull request by erdemyerebasmaz**
[Run CI](https://github.com/breez/misty-breez/actions/workflows/CI.yml)

Fixes #491

---

In release builds, Dart obfuscates class names like `PaymentsCubit` into short symbols like `IWa` to reduce binary size. `HydratedBloc` uses `runtimeType.toString()` as the default `storagePrefix`, which means it writes and reads state using the class name at runtime.

Since obfuscated builds change the `runtimeType` string, `HydratedBloc` can't find previously stored data (e.g., it looks for `PaymentsCubit` but finds `IWa` in storage). This leads to state loss between builds.

This PR adds a migration layer to map old obfuscated keys to stable identifiers. It also recommends overriding `storagePrefix` in cubits to ensure consistent keys across builds.

We have:
- Added explicit `storagePrefix` properties to override the default runtimeType-based keys
- Created a migration utility that runs during `HydratedBloc` initialization to map data from previous obfuscated keys to current keys
- Improved deserialization with better type handling and error recovery for enum values and null fields

These changes ensure user data persists correctly across app updates, even with code obfuscation enabled.

#### Changelist:
- feat: add stable storage prefixes to `HydratedMixin` `Cubits` 74f2cb6
```
  String get id => '';

  /// Storage prefix which can be overridden to provide a custom
  /// storage namespace.
  /// Defaults to [runtimeType] but should be overridden in cases
  /// where stored data should be resilient to obfuscation or persist
  /// between debug/release builds.
  String get storagePrefix => runtimeType.toString();

  /// `storageToken` is used as registration token for hydrated storage.
  /// Composed of [storagePrefix] and [id].
  @nonVirtual
  String get storageToken => '$storagePrefix$id';
```
- fix: improve enum and type handling for `JSON` deserialization 53655d2
- fix: add error handling to `toJson`/`fromJson` of `HydratedMixin` `Cubits` 06c953e
- fix: implement type casting and `null` handling for `HydratedMixin` `States` f1e47fc
- fix(`PaymentFilters`): correct the list equality check in `hasTypeFilters` 90cdbc9
  - Addresses an UI issue where filter sliver was shown incorrectly on Home page with the new default `PaymentFilters` values.
- feat: Create `HydratedBlocStorage` with migration support 575b9bc
- feat: simplify `enum` parsing in `SecurityState` and `PaymentData` models  d207b18
- fix: optimize `null` handling in LNURL metadata parsing a6fb7a7
- feat: simplify `JSON` parsing for `WalletInfo` & `BlockchainInfo` with centralized utility functions  1f346ac
- feat: use list-based approach for required field checks of `WalletInfo` & `BlockchainInfo` 9ef3c34
---

**Note:** This issue occurs sporadically during app updates. We found that certain update paths trigger the problem while others don't*, making it difficult to consistently reproduce in testing environments. I explored many approaches to this problem, and this solution is the one with the highest confidence level.

*: For example: TestFlight updates from build 6364.1 to versions below 6389.1 trigger the issue, while updates between later versions don't experience obfuscated Cubit IDs & states are hydrated w/o fail.

### CODE REVIEW

**Comment by erdemyerebasmaz** [comment]
### Testing Notes

#### Builds
- **iOS:**
  - Install `Version 0.1.1 (6364.1)` on TestFlight
- Android:
  - [TBD]

---

**After installing the build, change any of these settings:**
  - Change payment filters
  - Enable PIN, change 'Lock Automatically' duration, enable face id etc.
  - Change user profile name & avatar, expand 'Preferences' on navigation drawer
  - Hide amounts on Home page by clicking balance,
  - Go to Fiat Currencies and change preferred fiat currencies and their ordering.
  
**then upgrade to following builds in order:**
On **iOS:**
1.  `Version 0.1.1 (?.1)` on TestFlight
2. `Version 0.1.2 (?.1)` on TestFlight

On **Android:**
1. [TBD]
2. [TBD]

**and check if any of the settings did not carry over to new build after the update. If they didn't, please share logs.**

File: lib/utils/enum/enum_utils.dart [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+T parseEnum<T extends Enum>({
+  required dynamic value,
+  required List<T> enumValues,
+  required T defaultValue,
+  bool logFailures = false,
+}) {
+  // Handle numeric values (index-based)
+  if (value is int && value >= 0 && value < enumValues.length) {
+    return enumValues[value];
+  }
```
Comment (dangeross) [inline lib/utils/enum/enum_utils.dart:35]: Are enums normally stored as int or string? I wonder because inserting an enum in Rust could effect the representation here

**Review by dangeross — COMMENTED** [review]
Looks good. Seems to be some issues the CI has picked up

File: lib/utils/enum/enum_utils.dart (hunk 1 above)
Comment (erdemyerebasmaz) [reply lib/utils/enum/enum_utils.dart:35]: They are normally stored as string, with the enum `name`.

However, while it does not use this function, there is a case where the enum index(`int`) is used to store the enum.
`'appMode': appMode.index,`

**Review by dangeross — APPROVED** [review]
utACK

**Review by roeierez — APPROVED** [review]
