### PR TITLE
fix: prevent lock screen from getting stuck after PIN deactivation

### LINKED ISSUE #436: Prevent lock screen from getting stuck after PIN deactivation

### PR DESCRIPTION
**Pull request by erdemyerebasmaz**
Fixes #436

This PR resolves an issue where the app would become stuck on the lock screen after deactivating the PIN, with no way to unlock or exit. The problem was caused by a race condition in state management between PIN status and lock state.

#### Changes:
- Bypass PIN verification on `LockScreen` & `SecuredPage` is PIN is disabled
- Improve error handling in `testPin()` to properly recover from missing PIN data
- Update `clearPin()` to ensure consistent state transitions when disabling PIN

These changes ensure that if the PIN is disabled or missing from storage, the app will properly unlock itself instead of requiring verification of a non-existent PIN.

#### Testing Notes:
- Enable & Deactivate PIN on a previous device until app gets stuck.
- Update to following builds:
  - **Android:** Under artifacts on [Build Android](https://github.com/breez/misty-breez/actions/runs/13899789666)
  - **iOS:** v6350.1 on TestFlight.
- Confirm the app properly unlocks itself
- Attempt several times to get the app stuck again by enabling & deactivating PIN.

### CODE REVIEW

File: lib/cubit/security/security_cubit.dart [hunk 1]
```diff
@@ -153,7 +166,12 @@ class SecurityCubit extends Cubit<SecurityState> with HydratedMixin<SecurityStat
   @override
   SecurityState? fromJson(Map<String, dynamic> json) {
     final SecurityState state = SecurityState.fromJson(json);
-    _setLockState(state.pinStatus == PinStatus.enabled ? LockState.locked : LockState.unlocked);
+    // Only lock if PIN is enabled and not already in another lock state
+    if (state.pinStatus == PinStatus.enabled && state.lockState != LockState.unlocked) {
```
Comment (danielgranhao) [inline lib/cubit/security/security_cubit.dart:170]: Should we instead check if lockState is initial? Seems like it achieves the same but I find it more readable.

```suggestion
    if (state.pinStatus == PinStatus.enabled && state.lockState == LockState.initial) {
```

File: lib/cubit/security/security_cubit.dart [hunk 2]
```diff
@@ -49,17 +49,30 @@ class SecurityCubit extends Cubit<SecurityState> with HydratedMixin<SecurityStat
   }
 
   Future<bool> testPin(String pin) async {
+    // Allow access if PIN is disabled
```
Comment (roeierez) [inline lib/cubit/security/security_cubit.dart:52]: Since this method already takes a pin code it is weird that it also treats cases where the pin is not needed.
I think we should make the check on whether pin is needed or not before we show the pin widget to the user, hence before calling this method.
If we call this method then it should be strict with pin checking.

**Review by roeierez — CHANGES_REQUESTED** [review]

**Review by danielgranhao — COMMENTED** [review]
Looks good. Just a small detail

File: lib/cubit/security/security_cubit.dart (hunk 1 above)
Comment (erdemyerebasmaz) [reply lib/cubit/security/security_cubit.dart]: I have actually reverted to original approach 59dbafedcb1105cd4fa75eba1f920e7b5994a3b0

**Review by danielgranhao — APPROVED** [review]

File: lib/cubit/security/security_cubit.dart [hunk 3]
```diff
@@ -51,15 +51,21 @@ class SecurityCubit extends Cubit<SecurityState> with HydratedMixin<SecurityStat
   Future<bool> testPin(String pin) async {
     final String? storedPin = await keyChain.read(pinCodeKey);
     if (storedPin == null) {
-      _setLockState(LockState.locked);
-      throw SecurityStorageException();
+      _logger.warning('PIN not found in storage but state indicates enabled');
```
Comment (roeierez) [inline lib/cubit/security/security_cubit.dart:54]: Also here, I don't think we should clear the pin on this function. Do we really need to clear it?

**Comment by Nackoo2000** [comment]
Verified

**Review by roeierez — APPROVED** [review]
